config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :apps
  resources :appservers
  resources :servers
  resources :environments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appserver.rb
class Appserver < ApplicationRecord
  belongs_to :server

  has_many :apps
end

app/controllers/appservers_controller.rb
class AppserversController < ApplicationController
  before_action :set_appserver, only: [:show, :edit, :update, :destroy]
  before_action :sidebar_data

  # GET /appservers
  # GET /appservers.json
  def index
    @appservers = Appserver.all
  end

  # GET /appservers/1
  # GET /appservers/1.json
  def show
  end

  # GET /appservers/new
  def new
    @appserver = Appserver.new
  end

  # GET /appservers/1/edit
  def edit
  end

  # POST /appservers
  # POST /appservers.json
  def create
    @appserver = Appserver.new(appserver_params)

    respond_to do |format|
      if @appserver.save
        format.html { redirect_to @appserver, notice: 'Appserver was successfully created.' }
        format.json { render :show, status: :created, location: @appserver }
      else
        format.html { render :new }
        format.json { render json: @appserver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appservers/1
  # PATCH/PUT /appservers/1.json
  def update
    respond_to do |format|
      if @appserver.update(appserver_params)
        format.html { redirect_to @appserver, notice: 'Appserver was successfully updated.' }
        format.json { render :show, status: :ok, location: @appserver }
      else
        format.html { render :edit }
        format.json { render json: @appserver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appservers/1
  # DELETE /appservers/1.json
  def destroy
    @appserver.destroy
    respond_to do |format|
      format.html { redirect_to appservers_url, notice: 'Appserver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appserver
      @appserver = Appserver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appserver_params
      params.require(:appserver).permit(:name, :server_id)
    end
end

app/helpers/appservers_helper.rb
module AppserversHelper
end

app/views/appservers/_form.html.erb
<%= form_with(model: appserver, local: true) do |form| %>
  <% if appserver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appserver.errors.count, "error") %> prohibited this appserver from being saved:</h2>

      <ul>
      <% appserver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :appserver_name %>
  </div>

  <div class="field">
    <%= form.label :server_id %>
    <%= form.text_field :server_id, id: :appserver_server_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appservers/edit.html.erb
<h1>Editing Appserver</h1>

<%= render 'form', appserver: @appserver %>

<%= link_to 'Show', @appserver %> |
<%= link_to 'Back', appservers_path %>

app/views/appservers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appservers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Server</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appservers.each do |appserver| %>
      <tr>
        <td><%= appserver.name %></td>
        <td><%= appserver.server %></td>
        <td><%= link_to 'Show', appserver %></td>
        <td><%= link_to 'Edit', edit_appserver_path(appserver) %></td>
        <td><%= link_to 'Destroy', appserver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appserver', new_appserver_path %>

app/views/appservers/new.html.erb
<h1>New Appserver</h1>

<%= render 'form', appserver: @appserver %>

<%= link_to 'Back', appservers_path %>

app/views/appservers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appserver.name %>
</p>

<p>
  <strong>Server:</strong>
  <%= @appserver.server %>
</p>

<%= link_to 'Edit', edit_appserver_path(@appserver) %> |
<%= link_to 'Back', appservers_path %>