config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :apps
  resources :appservers
  resources :servers
  resources :environments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :app_name %>
  </div>

  <div class="field">
    <%= form.label :server_id %>
    <%= form.text_field :server_id, id: :app_server_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Server</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.server %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Appserver:</strong>
  <%= @app.appserver %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>